#!/bin/sh
SELF=$(readlink -f "$0")
HERE=${SELF%/*}
EXEC="${HERE}/usr/bin/sapmachine-jre-11.0.11/bin/java"
ARGS="--module-path=${HERE}/usr/bin/javafx-sdk-16/lib --add-modules=javafx.controls,javafx.graphics,javafx.fxml,javafx.web,javafx.base -jar ${HERE}/usr/bin/OrigamiGUI-1.13.0.jar"
exec "${EXEC}" $@ ${ARGS}
